### ISSUE TITLE
select on of the matches doesn't work

### ISSUE THREAD

**Issue by surfncode** [astropanic/Compline#5]
I've got this error in the console

```
 Traceback (most recent call last):
  File "./sublime_plugin.py", line 356, in run_
  File "./Compline.py", line 44, in run
Boost.Python.ArgumentError: Python argument types in
    Region.__init__(Region, float, long)
did not match C++ signature:
    __init__(_object*, long long)
    __init__(_object*, long long, long long, double)
    __init__(_object*, long long, long long)
```

**Comment by astropanic** [comment]
You didn't wrote which environment You're using, which Python version, which editor version.
I wrote this plugin 4 years ago.

I'm not using Sublime anymore, nor I'm using this plugin.

Either fix it Yourself as a python exercise, or find another plugin / editor that does the job for You.

**Comment by surfncode** [comment]
Sorry, my environement is:
Mac os 10.11.5 (el capitan)
This is on Sublime text 2 so the python version should be  2.6.

Would you consider accepting a pull request if I find the time to look into it ?

**Comment by astropanic** [comment]
Sure, will do.
